/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author Chamod
 */
public class Splash extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Splash.class.getName());

    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
        init();
        setResizable(false);
        setLocationRelativeTo(null);
        progress();
    }
    
    private void init() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/resource/logo7.png"));
        this.setIconImage(icon.getImage());
        setTitle("CarPlus");
    }
    
    private void progress() {
        new Thread(() -> {
            for (int i = 0; i <= 100; i++) {
                jProgressBar1.setValue(i);
                if (i == 10) {
                    jLabel2.setText("Loading...");
                } else if (i == 15) {
                    jLabel2.setText("Loading the Desgin....");
                } else if (i == 35) {
                    jLabel2.setText("Loading the Database....");
                } else if (i == 70) {
                    jLabel2.setText("Libraries and Resources loading....");
                } else if (i == 90) {
                    jLabel2.setText("Almost there");
                }
                try {
                    Thread.sleep(90);
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
//                    logger.warning(e.getMessage());
                }
            }
            new login().setVisible(true);
            this.dispose();
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 455, 5));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText(" ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 360, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/bg-splash.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
            System.err.println("Failed to initialize FlatLaf: " + e.getMessage());
        }
        java.awt.EventQueue.invokeLater(() -> new Splash().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
